# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule LexOffice.Model.ErrorMessage do
  @moduledoc """
  The structure with additional information about the result of the API request.
  """

  @derive [Poison.Encoder]
  defstruct [
    :message
  ]

  @type t :: %__MODULE__{
    :message => String.t
  }
end

defimpl Poison.Decoder, for: LexOffice.Model.ErrorMessage do
  def decode(value, _options) do
    value
  end
end

